apiVersion: blueprints.cloud.google.com/v1alpha1
kind: BlueprintMetadata
metadata:
  name: marketplace-tools
  annotations:
    autogenSpecType: SINGLE_VM
    config.kubernetes.io/local-config: "true"
spec:
  info:
    title: "Couchbase Server Terraform Module"
    version: "1.0"
    actuationTool:
      flavor: Terraform
      version: ">= 1.2"
    description: {}
    softwareGroups:
      - type: SG_OS
        software:
          - title: Ubuntu
            version: "20.04"
      - software:
        - title: Couchbase Server
          version: "7.6.5"
  content: {}
  interfaces:
    variables:
      - name: project_id
        description: The ID of the project in which to provision resources.
        varType: string
        required: true
      - name: goog_cm_deployment_name
        description: The name of the deployment and VM instance.
        varType: string
        required: true
      - name: source_image
        description: "The image name for the disk of the VM Instance"
        varType: string
        defaultValue: projects/couchbase-public/global/images/couchbase-server-byol-v20250316
      - name: zone
        description: The zone for the solution to be deployed.
        varType: string
        required: true
      - name: boot_disk_type
        description: The boot disk type for the VM instance.
        varType: string
        defaultValue: pd-standard
      - name: boot_disk_size
        description: The boot disk size for the VM instance in GBs
        varType: integer
        defaultValue: 20
      - name: machine_type
        description: The machine type to create, e.g. e2-small
        varType: string
        defaultValue: n1-standard-4
      - name: networks
        description: The network name to attach the VM instance.
        varType: list(string)
        defaultValue:
          - default
      - name: sub_networks
        description: The sub network name to attach the VM instance.
        varType: list(string)
        defaultValue: []
      - name: server_node_count
        description: "The number of Couchbase Server nodes to deploy"
        varType: number
        defaultValue: 3
      - name: data_disk_type
        description: The data disk type for the VM instance.
        varType: string
        defaultValue: pd-standard
      - name: data_disk_size
        description: The data disk size for the VM instance in GBs
        varType: integer
        defaultValue: 20
      - name: server_version
        description: The version of Couchbase Server to use
        varType: string
        defaultValue: "7.6.5"
      - name: server_username
        description: "The username for logging into Couchbase Server"
        varType: string
      - name: server_password
        description: "The password for logging into Couchbase Server"
        varType: string
      - name: existing_rally_url
        description: "The url to an existing Couchbase Server cluster to join"
        varType: string
      - name: data_service
        description: "Enable the data service in couchbase server"
        varType: bool
        defaultValue: true
      - name: index_service
        description: "Enable the index service in couchbase server"
        varType: bool
        defaultValue: true
      - name: query_service
        description: "Enable the query service in couchbase server"
        varType: bool
        defaultValue: true
      - name: eventing_service
        description: "Enable the eventing service in couchbase server"
        varType: bool
        defaultValue: false
      - name: fts_service
        description: "Enable the full text search service in couchbase server"
        varType: bool
        defaultValue: false
      - name: analytics_service
        description: "Enable the analytics service in couchbase server"
        varType: bool
        defaultValue: false
      - name: backup_service
        description: "Enable the backup service in couchbase server"
        varType: bool
        defaultValue: false
      - name: access_cidr
        description: "CIDR for ingress into the Couchbase Cluster"
        varType: string
        defaultValue: "0.0.0.0/0"
      - name: svc_account
        description: "The service account to use/create"
        varType: string
        defaultValue: "couchbase-sa"
