imports:
  - path: couchbase.py
    name: couchbase.py
resources:
  - name: test-couchbase-deployment
    type: couchbase.py
    properties:
      name: couchbase-server-test
      serverNodeCount: 3
      serverNodeType: n1-standard-4
      serverDiskSize: 20
      serverVersion: 7.1.3
      username: couchbase
      password: foo123!
      accessCIDR: 0.0.0.0/0
      imageFamily: couchbase-server-hourly-pricing
      # This svcAccount is for Local Testing.  test_config.yaml should use the specified account for GCP's submittal process
      svcAccount: couchbase-dev-test@couchbase-dev.iam.gserviceaccount.com
outputs:
  - name: runtimeConfigName
    value: $(ref.test-couchbase-deployment.runtimeConfigName)
  - name: ruleTag
    value: $(ref.test-couchbase-deployment.firewallRuleTag)
