imports:
  - path: couchbase.py
    name: couchbase.py

resources:
  - name: test-couchbase-deployment
    type: couchbase.py
    properties: 
      name: couchbase-gateway-test
      serverNodeCount: 3
      serverNodeType: n1-standard-4
      serverDiskSize: 20
      serverVersion: 3.0.5
      username: 'couchbase'
      password: 'foo123!'
      accessCIDR: 0.0.0.0/0
      couchbaseConnectionString: ''
      bucket: 'travel-sample'
      # This svcAccount is for GCP Submit.  There are other test_configs for local testing
      svcAccount: couchbase-server-hourly@cloud-launcher-verifier-prd.iam.gserviceaccount.com
outputs:
  - name: runtimeConfigName
    value: $(ref.test-couchbase-deployment.runtimeConfigName)
  - name: ruleTag
    value: $(ref.test-couchbase-deployment.firewallRuleTag)
