imports:
  - path: couchbase.py
    name: couchbase.py

resources:
  - name: test-couchbase-deployment
    type: couchbase.py
    properties: 
      name: couchbase-gateway-test
      serverNodeCount: 3
      serverNodeType: n1-standard-4
      serverDiskSize: 20
      serverVersion: 3.0.3
      username: 'couchbase'
      password: 'foo123!'
      accessCIDR: 0.0.0.0/0
      couchbaseConnectionString: ''
      bucket: 'travel-sample'
      svcAccount: 'couchbase-dev-test@couchbase-dev.iam.gserviceaccount.com'
outputs:
  - name: runtimeConfigName
    value: $(ref.test-couchbase-deployment.runtimeConfigName)
  - name: ruleTag
    value: $(ref.test-couchbase-deployment.firewallRuleTag)
