# This is a basic workflow to help you get started with Actions

name: AWS - CouchbaseServerAndSyncGatewayBYOL

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
    paths:
      - 'aws/CouchbaseServerAndSyncGateway/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'aws/CouchbaseServerAndSyncGateway/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  AWSLaunch:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Echo $GITHUB_WORKSPACE
        run: echo "$GITHUB_WORKSPACE"
      # Runs a set of commands using the runners shell
      - name: Deploy To AWS
        timeout-minutes: 15
        run: |
            ${GITHUB_WORKSPACE}/aws/CouchbaseServerAndSyncGateway/deploy.sh aws-cb-sg-mp-byol byol
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-east-1'
          AWS_REGION: 'us-east-1'
      - name: Teardown From AWS
        timeout-minutes: 15
        run: |
            ${GITHUB_WORKSPACE}/aws/CouchbaseServerAndSyncGateway/backout.sh aws-cb-sg-mp-byol
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-east-1'
          AWS_REGION: 'us-east-1'
