name: Azure - CouchbaseServer

on:
  push:
    branches: [main]
    paths:
      - "azure/CouchbaseServer-Application/**"
  workflow_dispatch:
jobs:
  ServerLaunchBYOL:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Echo $GITHUB_WORKSPACE
        run: echo "$GITHUB_WORKSPACE"
      - name: Deploy To Azure
        timeout-minutes: 20
        uses: azure/CLI@v1
        with:
          inlineScript: |
            bash ${GITHUB_WORKSPACE}/azure/CouchbaseServer-Application/test/deploy.sh -l eastus -p ${GITHUB_WORKSPACE}/azure/CouchbaseServer-Application/test/parameters.json -g cb-mkt-test-hourly -n ga-cbs-app-byol
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: Install CouchbaseVerifier
        run: |
          dotnet tool install CouchbaseVerifier --global --version 1.0.3
      - name: Run Default Tests
        run: |
          DNS=$(az deployment group show -g cb-mkt-test-hourly -n ga-cbs-app-byol --query properties.outputs.serverAdminURL.value | jq -r)
          USERNAME=$(cat ${GITHUB_WORKSPACE}/azure/CouchbaseServer-Application/test/parameters.json | jq -r '.serverUsername.value')
          PASSWORD=$(cat ${GITHUB_WORKSPACE}/azure/CouchbaseServer-Application/test/parameters.json | jq -r '.serverPassword.value')
          CouchbaseVerifier verify --host "${DNS}" -u "$USERNAME" -p "$PASSWORD" -d ${GITHUB_WORKSPACE}/azure/CouchbaseServer-Application/test/verifier_tests/Defaults.json
      - name: Teardown From Azure
        if: always()
        uses: azure/CLI@v1
        with:
          inlineScript: |
            bash ${GITHUB_WORKSPACE}/azure/CouchbaseServer-Application/test/backout.sh -g cb-mkt-test-hourly -s
  ServerLaunchHourly:
    runs-on: ubuntu-latest
    needs: ServerLaunchBYOL
    steps:
      - uses: actions/checkout@v2
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Echo $GITHUB_WORKSPACE
        run: echo "$GITHUB_WORKSPACE"
      - name: Deploy To Azure
        timeout-minutes: 20
        uses: azure/CLI@v1
        with:
          inlineScript: |
            ${GITHUB_WORKSPACE}/azure/CouchbaseServer-Application/test/deploy.sh -l eastus -p ${GITHUB_WORKSPACE}/azure/CouchbaseServer-Application/test/mds_parameters.json -g cb-mkt-test-hourly -n ga-cbs-sg-app-hourly-two
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: Install CouchbaseVerifier
        run: |
          dotnet tool install CouchbaseVerifier --global --version 1.0.3
      - name: Run mds tests
        run: |
          DNS=$(az deployment group show -g cb-mkt-test-hourly -n ga-cbs-sg-app-hourly-two --query properties.outputs.serverAdminURL.value | jq -r)
          USERNAME=$(cat ${GITHUB_WORKSPACE}/azure/CouchbaseServer-Application/test/mds_parameters.json | jq -r '.serverUsername.value')
          PASSWORD=$(cat ${GITHUB_WORKSPACE}/azure/CouchbaseServer-Application/test/mds_parameters.json | jq -r '.serverPassword.value')
          CouchbaseVerifier verify --host "${DNS}" -u "$USERNAME" -p "$PASSWORD" -d ${GITHUB_WORKSPACE}/azure/CouchbaseServer-Application/test/verifier_tests/mds_tests.json
      - name: Teardown From Azure
        uses: azure/CLI@v1
        if: always()
        with:
          inlineScript: |
            ${GITHUB_WORKSPACE}/azure/CouchbaseServer-Application/test/backout.sh -g cb-mkt-test-hourly -s
  ServerTestBadMDS:
    runs-on: ubuntu-latest
    needs: ServerLaunchHourly
    steps:
      - uses: actions/checkout@v2
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Echo $GITHUB_WORKSPACE
        run: echo "$GITHUB_WORKSPACE"
      - name: Deploy To Azure
        timeout-minutes: 20
        uses: azure/CLI@v1
        with:
          inlineScript: |
            ${GITHUB_WORKSPACE}/azure/CouchbaseServer-Application/test/deploy.sh -l eastus -p ${GITHUB_WORKSPACE}/azure/CouchbaseServer-Application/test/test_parameters/bad_mds_params.json -g cb-mkt-test-hourly -n ga-cbs-sg-app-hourly-three
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: Install CouchbaseVerifier
        run: |
          dotnet tool install CouchbaseVerifier --global --version 1.0.3
      - name: Run mds tests
        run: |
          DNS=$(az deployment group show -g cb-mkt-test-hourly -n ga-cbs-sg-app-hourly-three --query properties.outputs.serverAdminURL.value | jq -r)
          USERNAME=$(cat ${GITHUB_WORKSPACE}/azure/CouchbaseServer-Application/test/test_parameters/bad_mds_params.json | jq -r '.serverUsername.value')
          PASSWORD=$(cat ${GITHUB_WORKSPACE}/azure/CouchbaseServer-Application/test/test_parameters/bad_mds_params.json | jq -r '.serverPassword.value')
          CouchbaseVerifier verify --host "${DNS}" -u "$USERNAME" -p "$PASSWORD" -d ${GITHUB_WORKSPACE}/azure/CouchbaseServer-Application/test/verifier_tests/bad_mds_tests.json
      - name: Teardown From Azure
        uses: azure/CLI@v1
        if: always()
        with:
          inlineScript: |
            ${GITHUB_WORKSPACE}/azure/CouchbaseServer-Application/test/backout.sh -g cb-mkt-test-hourly -s