name: Azure - CouchbaseSyncGateway

on:
  push:
    branches: [ main ]
    paths:
      - 'azure/CouchbaseSyncGateway-Application/**'
  workflow_dispatch:
jobs:
  SyncGatewayLaunch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Azure Login
        uses: azure/login@v1
        with: 
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Deploy To Azure
        timeout-minutes: 30
        uses: azure/CLI@v1
        with:
          inlineScript: |
            COUCHBASESERVER=$(${GITHUB_WORKSPACE}/azure/CouchbaseSyncGateway-Application/test/createServer.sh -g cb-mkt-sg-test -l eastus)
            SERVER="couchbase://$(echo $COUCHBASESERVER | jq -r '.ip')"
            USER=$(echo $COUCHBASESERVER | jq -r '.couchbaseUser')
            PASS=$(echo $COUCHBASESERVER | jq -r '.couchbasePassword')
            echo $COUCHBASESERVER
            bash ${GITHUB_WORKSPACE}/azure/CouchbaseSyncGateway-Application/test/deploy.sh -l eastus -p ${GITHUB_WORKSPACE}/azure/CouchbaseSyncGateway-Application/test/parameters.json -g cb-mkt-sg-test -n cb-mkt-test-sg -s $SERVER -b default -d default -u $USER -q $PASS -v 2.8.2
      - name: Teardown From Azure
        uses: azure/CLI@v1
        if: always()
        with:
          inlineScript: |
            bash ${GITHUB_WORKSPACE}/azure/CouchbaseServer-Application/test/backout.sh -g cb-mkt-sg-test -s
