name: Azure Template Verification

on:
  pull_request:
    paths:
      - "azure/CouchbaseServer-Application/**"
      - "azure/CouchbaseSyncGateway-Application/**"
      - "azure/CouchbaseServerAndSyncGateway-Application/**"
  workflow_dispatch:
jobs:
  # Job one, build the docker container
  VerifyServerTemplate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker Container
        run: docker build -t az-verification --file ${GITHUB_WORKSPACE}/azure/Dockerfile ${GITHUB_WORKSPACE}/azure
      - name: Build server package without zip
        run: |
          bash ${GITHUB_WORKSPACE}/azure/CouchbaseServer-Application/makeArchives.sh \
                                         -l byol \
                                         -s cbs-2022-byol-pre-installed \
                                         -p couchbase \
                                         -o couchbase-server-enterprise \
                                         -v latest
      - name: Check files exist
        run: ls -l "${GITHUB_WORKSPACE}"/build/azure/CouchbaseServer/
      - name: verify server template
        run: docker run --rm --mount type=bind,source="${GITHUB_WORKSPACE}/build/azure/CouchbaseServer/azure-cbs-archive-byol",target=/template az-verification
      - name: Build server package without license and not zipped
        run: |
          bash ${GITHUB_WORKSPACE}/azure/CouchbaseServer-Application/makeArchives.sh \
                                         -u \
                                         -s cbs-2022-byol-pre-installed \
                                         -p couchbase \
                                         -o couchbase-server-enterprise \
                                         -v latest
      - name: Check files exist
        run: ls -l "${GITHUB_WORKSPACE}"/build/azure/CouchbaseServer/
      - name: verify server template
        run: docker run --rm --mount type=bind,source="${GITHUB_WORKSPACE}/build/azure/CouchbaseServer/azure-cbs-archive-unlicensed",target=/template az-verification

      - name: Build gateway package without zip
        run: |
          bash ${GITHUB_WORKSPACE}/azure/CouchbaseSyncGateway-Application/makeArchives.sh \
                                          -l byol \
                                          -p couchbase \
                                          -g couchbase-sync-gateway-enterprise \
                                          -i latest \
                                          -u cb-gateway-2022-pre-installed-byol \
      - name: verify gateway template
        run: docker run --rm --mount type=bind,source="${GITHUB_WORKSPACE}/build/azure/CouchbaseSyncGateway/azure-sg-archive-byol",target=/template az-verification
      
      - name: Build combined package without zip
        run: |
          bash ${GITHUB_WORKSPACE}/azure/CouchbaseServerAndSyncGateway-Application/makeArchives.sh \
                                          -l byol \
                                          -s byol_2019 \
                                          -p couchbase \
                                          -o couchbase-server-enterprise \
                                          -v 18.4.0 \
                                          -g couchbase-sync-gateway-enterprise \
                                          -i 18.4.0 \
                                          -u byol_2019
      - name: verify combined template
        run: docker run --rm --mount type=bind,source="${GITHUB_WORKSPACE}/build/azure/CouchbaseServerAndSyncGateway/azure-cbs-archive-byol",target=/template az-verification                
