name: Azure - CouchbaseServer

on:
  push:
    branches: [main]
    paths:
      - "azure/CouchbaseServer-Application/**"
  workflow_dispatch:
jobs:
  ServerLaunchBYOL:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Echo $GITHUB_WORKSPACE
        run: echo "$GITHUB_WORKSPACE"
      - name: Deploy To Azure
        timeout-minutes: 20
        uses: azure/CLI@v1
        with:
          inlineScript: |
            bash ${GITHUB_WORKSPACE}/azure/CouchbaseServer-Application/test/deploy.sh -l eastus -p ${GITHUB_WORKSPACE}/azure/CouchbaseServer-Application/test/parameters.json -g cb-mkt-test-hourly -n ga-cbs-app-byol
      - name: Teardown From Azure
        uses: azure/CLI@v1
        with:
          inlineScript: |
            bash ${GITHUB_WORKSPACE}/azure/CouchbaseServer-Application/test/backout.sh -g cb-mkt-test-hourly -s
  ServerLaunchHourly:
    runs-on: ubuntu-latest
    needs: AzureLaunch
    steps:
      - uses: actions/checkout@v2
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Echo $GITHUB_WORKSPACE
        run: echo "$GITHUB_WORKSPACE"
      - name: Deploy To Azure
        timeout-minutes: 20
        uses: azure/CLI@v1
        with:
          inlineScript: |
            ${GITHUB_WORKSPACE}/azure/CouchbaseServer-Application/test/deploy.sh -l eastus -p ${GITHUB_WORKSPACE}/azure/CouchbaseServer-Application/test/test_parameters/mds_parameters.json -g cb-mkt-test-hourly -n ga-cbs-sg-app-hourly-two
      - name: Teardown From Azure
        uses: azure/CLI@v1
        with:
          inlineScript: |
            ${GITHUB_WORKSPACE}/azure/CouchbaseServer-Application/test/backout.sh -g cb-mkt-test-hourly -s
