# This is a basic workflow to help you get started with Actions

name: Azure - CouchbaseServerAndSyncGatewayBYOL

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
    paths:
      - 'azure/CouchbaseServerAndSyncGateway-Application/**'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  AzureLaunch:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Azure Login
        uses: azure/login@v1
        with: 
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Echo $GITHUB_WORKSPACE
        run: echo "$GITHUB_WORKSPACE"
      # Runs a set of commands using the runners shell
      - name: Deploy To Azure
        timeout-minutes: 15
        uses: azure/CLI@v1
        with:
          inlineScript: |
            ${GITHUB_WORKSPACE}/azure/CouchbaseServerAndSyncGateway-Application/test/deploy.sh -l eastus -p ${GITHUB_WORKSPACE}/azure/CouchbaseServerAndSyncGateway-Application/test/parameters.json -g cb-mkt-test-byol -n ga-cbs-sg-app-byol
      - name: Teardown From Azure
        uses: azure/CLI@v1
        with:
          inlineScript: |
            ${GITHUB_WORKSPACE}/azure/CouchbaseServerAndSyncGateway-Application/test/backout.sh -g cb-mkt-test-byol -s

  AzureNoSyncGateway:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: AzureLaunch
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Azure Login
        uses: azure/login@v1
        with: 
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Echo $GITHUB_WORKSPACE
        run: echo "$GITHUB_WORKSPACE"
      # Runs a set of commands using the runners shell
      - name: Deploy To Azure
        timeout-minutes: 15
        uses: azure/CLI@v1
        with:
          inlineScript: |
            ${GITHUB_WORKSPACE}/azure/CouchbaseServerAndSyncGateway-Application/test/deploy.sh -l eastus -p ${GITHUB_WORKSPACE}/azure/CouchbaseServerAndSyncGateway-Application/test/test_parameters/NoSyncGateway.json -g cb-mkt-test-byol -n ga-cbs-no-sg-app-byol
      - name: Teardown From Azure
        uses: azure/CLI@v1
        with:
          inlineScript: |
            ${GITHUB_WORKSPACE}/azure/CouchbaseServerAndSyncGateway-Application/test/backout.sh -g cb-mkt-test-byol -s
  AzureLaunchHourly:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: AzureNoSyncGateway
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Azure Login
        uses: azure/login@v1
        with: 
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Echo $GITHUB_WORKSPACE
        run: echo "$GITHUB_WORKSPACE"
      # Runs a set of commands using the runners shell
      - name: Deploy To Azure
        timeout-minutes: 15
        uses: azure/CLI@v1
        with:
          inlineScript: |
            ${GITHUB_WORKSPACE}/azure/CouchbaseServerAndSyncGateway-Application/test/deploy.sh -l eastus -p ${GITHUB_WORKSPACE}/azure/CouchbaseServerAndSyncGateway-Application/test/test_parameters/HourlyPricing.json -g cb-mkt-test-byol -n ga-cbs-sg-app-hourly -h test
      - name: Teardown From Azure
        uses: azure/CLI@v1
        with:
          inlineScript: |
            ${GITHUB_WORKSPACE}/azure/CouchbaseServerAndSyncGateway-Application/test/backout.sh -g cb-mkt-test-byol -s
  AzureNoSyncGatewayHourly:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: AzureLaunchHourly
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Azure Login
        uses: azure/login@v1
        with: 
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Echo $GITHUB_WORKSPACE
        run: echo "$GITHUB_WORKSPACE"
      # Runs a set of commands using the runners shell
      - name: Deploy To Azure
        timeout-minutes: 15
        uses: azure/CLI@v1
        with:
          inlineScript: |
            ${GITHUB_WORKSPACE}/azure/CouchbaseServerAndSyncGateway-Application/test/deploy.sh -l eastus -p ${GITHUB_WORKSPACE}/azure/CouchbaseServerAndSyncGateway-Application/test/test_parameters/NoSyncGateway.json -g cb-mkt-test-byol -n ga-cbs-sg-app-hourly -h test
      - name: Teardown From Azure
        uses: azure/CLI@v1
        with:
          inlineScript: |
            ${GITHUB_WORKSPACE}/azure/CouchbaseServerAndSyncGateway-Application/test/backout.sh -g cb-mkt-test-byol -s            