# This is a basic workflow to help you get started with Actions

name: Azure Release Workflow

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  release:
    types: [created]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  azure-release:
    if: "endsWith(github.event.release.tag_name, 'azure') || endsWith(github.event.release.tag_name, 'all')"
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Create Build Directory
        run: mkdir ${GITHUB_WORKSPACE}/build
      # Runs a set of commands using the runners shell
      - name: Build BYOL Combined Package
        run: |
          bash ${GITHUB_WORKSPACE}/azure/CouchbaseServerAndSyncGateway-Application/makeArchives.sh \
                                          -l byol \
                                          -s byol_2019 \
                                          -p couchbase \
                                          -o couchbase-server-enterprise \
                                          -v 18.4.0 \
                                          -g couchbase-sync-gateway-enterprise \
                                          -i 18.4.0 \
                                          -u byol_2019 \
                                          -z
      - name: Build Hourly Combined Package
        run: |
          bash ${GITHUB_WORKSPACE}/azure/CouchbaseServerAndSyncGateway-Application/makeArchives.sh \
                                        -l hourly-pricing \
                                        -s hourly_pricing_mar19 \
                                        -p couchbase \
                                        -o couchbase-server-enterprise \
                                        -v 18.4.0 \
                                        -g couchbase-sync-gateway-enterprise \
                                        -i 18.4.0 \
                                        -u hourly_pricing_mar19 \
                                        -z
      - name: Build BYOL CBS Package
        run: |
          bash ${GITHUB_WORKSPACE}/azure/CouchbaseServer-Application/makeArchives.sh \
                                          -l byol \
                                          -s cbs-2022-byol-pre-installed \
                                          -p couchbase \
                                          -o couchbase-server-enterprise \
                                          -v latest \
                                          -z
      - name: Build Hourly CBS Package - Gold Support
        run: |
          bash ${GITHUB_WORKSPACE}/azure/CouchbaseServer-Application/makeArchives.sh \
                                        -l hourly-pricing-gold-support \
                                        -s cbs-2022-gold-support \
                                        -p couchbase \
                                        -o couchbase-server-enterprise \
                                        -v latest  \
                                        -z
      - name: Build Hourly CBS Package - Silver Support
        run: |
          bash ${GITHUB_WORKSPACE}/azure/CouchbaseServer-Application/makeArchives.sh \
                                        -l hourly-pricing-silver-support \
                                        -s cbs-2022-silver-support \
                                        -p couchbase \
                                        -o couchbase-server-enterprise \
                                        -v latest  \
                                        -z                                         
      - name: Build BYOL Gateway Package
        run: |
          bash ${GITHUB_WORKSPACE}/azure/CouchbaseSyncGateway-Application/makeArchives.sh \
                                          -l byol \
                                          -p couchbase \
                                          -g couchbase-sync-gateway-enterprise \
                                          -i latest \
                                          -u cb-gateway-2022-pre-installed-byol \
                                          -z
      - name: Build Hourly Gateway Package - Gold Support
        run: |
          bash ${GITHUB_WORKSPACE}/azure/CouchbaseSyncGateway-Application/makeArchives.sh \
                                        -l hourly-pricing-gold-support \
                                        -p couchbase \
                                        -g couchbase-sync-gateway-enterprise \
                                        -i latest \
                                        -u cb-gateway-2022-pre-installed-gold \
                                        -z
      - name: Build Hourly Gateway Package - Silver Support
        run: |
          bash ${GITHUB_WORKSPACE}/azure/CouchbaseSyncGateway-Application/makeArchives.sh \
                                        -l hourly-pricing-silver-support \
                                        -p couchbase \
                                        -g couchbase-sync-gateway-enterprise \
                                        -i latest \
                                        -u cb-gateway-2022-pre-installed-silver \
                                        -z                                                                                 
      - name: Upload Combined BYOL Package
        id: upload-combined-byol-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with: 
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./build/azure/CouchbaseServerAndSyncGateway/azure-combined-archive-byol.zip
          asset_name: azure-combined-archive-byol.zip
          asset_content_type: application/zip
      - name: Upload Combined Hourly Package
        id: upload-combined-hourly-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with: 
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./build/azure/CouchbaseServerAndSyncGateway/azure-combined-archive-hourly-pricing.zip
          asset_name: azure-combined-archive-hourly-pricing.zip
          asset_content_type: application/zip
      - name: Upload CBS BYOL Package
        id: upload-cbs-byol-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with: 
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./build/azure/CouchbaseServer/azure-cbs-archive-byol.zip
          asset_name: azure-cbs-archive-byol.zip
          asset_content_type: application/zip
      - name: Upload CBS Hourly Package - Gold
        id: upload-cbs-hourly-asset-gold
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with: 
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./build/azure/CouchbaseServer/azure-cbs-archive-hourly-pricing-gold-support.zip
          asset_name: azure-cbs-archive-hourly-pricing-gold-support.zip
          asset_content_type: application/zip
      - name: Upload CBS Hourly Package - Silver
        id: upload-cbs-hourly-asset-silver
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with: 
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./build/azure/CouchbaseServer/azure-cbs-archive-hourly-pricing-silver-support.zip
          asset_name: azure-cbs-archive-hourly-pricing-silver-support.zip
          asset_content_type: application/zip          
      - name: Upload Gateway BYOL Package
        id: upload-sg-byol-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with: 
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./build/azure/CouchbaseSyncGateway/azure-sg-archive-byol.zip
          asset_name: azure-sg-archive-byol.zip
          asset_content_type: application/zip
      - name: Upload Gateway Hourly Package - Silver
        id: upload-sg-hourly-asset-silver
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with: 
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./build/azure/CouchbaseSyncGateway/azure-sg-archive-hourly-pricing-silver-support.zip
          asset_name: azure-sg-archive-hourly-pricing-silver-support.zip
          asset_content_type: application/zip
      - name: Upload Gateway Hourly Package - Gold
        id: upload-sg-hourly-asset-gold
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with: 
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./build/azure/CouchbaseSyncGateway/azure-sg-archive-hourly-pricing-gold-support.zip
          asset_name: azure-sg-archive-hourly-pricing-gold-support.zip
          asset_content_type: application/zip                                 